### ISSUE TITLE
blockly implementation

### ISSUE THREAD

**Issue by cubecraft00** [Entkenntnis/robot-karol-online#552]
**Hello**

I would like to know how did you manage to implement without having the error `cannot use import outside a module` as written in the forum that you launched a year ago

_Thanks for your answer in advance_

**Cordially**

**Comment by Entkenntnis** [comment]
I have updated my answer in https://github.com/nbudin/react-blockly/issues/71#issuecomment-1188935219 to point to the correct file. You can copy my solution and adapt it to your use case
