### ISSUE TITLE
Possible Bug in Assignment "Secret"? 

### ISSUE THREAD

**Issue by Kirua-Sama** [Entkenntnis/robot-karol-online#703]
DE: Aufgabe: Geheimnis
Assignment: Secret

There might be a bug in the assignment "Secret". The engine does not mark the assignment as completed after all bricks have been removed. 

The assignment is: "What lies behind the bricks? Remove the bricks to peek behind and uncover the secret."

Issue: After successfully removing all bricks it says -> Assignment not completed.

**Comment by Entkenntnis** [comment]
After peeking behind the bricks, you will see that you have to place a mark at a specifiy position. Then write a program that does not remove the bricks, but marks the field instead to complete the assignment.

I do agree that the wording here could be better.

**Comment by Kirua-Sama** [comment]
Thank you for the quick clarification
Suggestion for the wording: "Find the secret spot to mark and place back the boxes"

**Comment by Entkenntnis** [comment]
Thank you for the report,

fixed in https://github.com/Entkenntnis/robot-karol-online/commit/cde0b00d4e053f84ad515d29d199289e65dfc3a9
