### ISSUE TITLE
Don't know what to do in Assignment Gap

### ISSUE THREAD

**Issue by Kirua-Sama** [Entkenntnis/robot-karol-online#705]
Assignment Gap - DE: Lücke
Don't know what to do, can't finish the assignment
I fixed the stair -> assignment not completed
I fixed the stair and mark the removed last brick -> assignment not completed
I build new stairs to be able to mark the last brick -> assignment not completed

**Comment by Kirua-Sama** [comment]
ok thank you, I thought I have to fixed the mistake.
I didn't expect to rebuild it to the previous state

Description suggestion:
Mission is to overcome the 2 bricks and rebuild the stairs to the initial state.

Now I have finished it, thx

**Comment by Entkenntnis** [comment]
added description
