### ISSUE TITLE
Missing assignment description in assignment Additional Task

### ISSUE THREAD

**Issue by Kirua-Sama** [Entkenntnis/robot-karol-online#706]
The assignment description of assignment Additional Task (DE: Zusatzaufgabe) displays just "Source: #UJRX"
I searched on google for #UJRX but couldn't find anything related to this assignment.

**Comment by Entkenntnis** [comment]
This assignment should be some kind of "riddle" to figure out the right algorithm, but a bit of explaination wouldn't hurt, either

**Comment by Kirua-Sama** [comment]
yes, I was able to solve it.
Suggestion: "Find 1 right algorithm for all 4 worlds."

**Comment by Entkenntnis** [comment]
added description
