### ISSUE TITLE
Effort estimation for variables and mathematical operators 

### ISSUE THREAD

**Issue by AljoshaVieth** [Entkenntnis/robot-karol-online#708]
Hello, 
I am in the process of looking for an environment for an educational institution. Robot Karol online would be very suitable for this, but we lack the possibility to create variables (at least simple numerical values) and to change them with mathematical operators. Also, some kind of simple list/array would be very helpful. 

How do you estimate the effort required to implement these features? 
If the effort is justifiable, I would do the implementation myself.

**Comment by Entkenntnis** [comment]
Hello! These features are on the roadmap and I have already started to set up the IDE for it. I can give you a summary of the plans I have.

The initial support will only include the **java** mode in **German**. Because the main focus is on beginners, the block mode and the robot karol text mode is feature frozen.

So my first question: Will adding variables and mathematical operators in the java mode in German be sufficient for your use case? If yes, then we can start a collaboration here :)

I will give you a small technical summary in the follow up post.

**Comment by Entkenntnis** [comment]
If you haven't looked into it yet, this is how the mode looks like right now:

![grafik](https://github.com/Entkenntnis/robot-karol-online/assets/13507950/8bb2786f-571b-4c9c-80b3-9a4c5ec3d93a)

**Comment by AljoshaVieth** [comment]
Hey, thank you for your fast reply!
I think advanced features in Java and German are perfectly fine, since the lessons are also in German and focused on Java.
Variables and mathematical operators are the mist important part and I think would be enough. However, some simple implementation of an array would also be nice, I think an int[] would be enough.

**Comment by Entkenntnis** [comment]
I'm starting to work on it in #709

**Comment by Entkenntnis** [comment]
@AljoshaVieth I'm quite busy the next few weeks.

You can start by taking a look at https://karol.arrrg.de/test-java.html and the file https://github.com/Entkenntnis/robot-karol-online/blob/cc3f76b16ec5242d55a92d3ffb8fda61f4585343/lib/language/compileJava.ts. These two should give you a good starting point for working on this.

I'm admitting that the compiler code was written in a bit of a hurry and could need a bit of cleaning up in some spaces, it's also not perfectly structured yet. I'm interested in your estimation if you feel confident working on this code base?

**Comment by Entkenntnis** [comment]
Some progress is made:

![grafik](https://github.com/Entkenntnis/robot-karol-online/assets/13507950/68b08cf1-ff85-4d98-a77c-8c92eb4ffede)

![grafik](https://github.com/Entkenntnis/robot-karol-online/assets/13507950/7006de14-f3d5-459d-94e2-e9be99b2fbcb)
